#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
source ./scripts/version
mkdir -p bin
CGO_ENABLED=0 go build -trimpath -buildvcs=false -ldflags "-X main.buildVersion=${VERSION} -s -w" -o bin/metadata-cni-ipam .
