#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
source ./scripts/version

output_dir="dist/${VERSION}"
binary_name="metadata-cni-ipam-${VERSION}-linux-amd64"
mkdir -p "$output_dir"

GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build \
    -trimpath -buildvcs=false \
    -ldflags "-buildid= -X main.buildVersion=${VERSION} -s -w" \
    -o "$output_dir/$binary_name" .
chmod 0755 "$output_dir/$binary_name"
sha256sum "$output_dir/$binary_name" > "$output_dir/SHA256SUMS"
